// JPMN is short for JP Mining Note
var JPMNOpts = (function (my) {

  my.settings = {
      // RESERVED KEYS (by anki):
      // - e (edit)
      // - r (replay)
      // - t (stats)
      // - y (sync)
      // - i (card info)
      // - o (options)
      // - a (add)
      // - s (idk exactly what this does tbh)
      // - d (deck)
      // - f (filtered deck options)
      // - v (play recorded voice)
      // - b (browse)
      // - m (menu)
      // - 1, 2, 3, 4 (again, hard, good, easy)
      // - 5 (pause audio)
      // - 6 (audio -5s)
      // - 7 (audio +5s)
      // - space (good)
      // - enter (good)
      //
      // RESERVED KEYS (by AJT Flexible grading):
      // - u (undo)
      // - h, j, k, l: hard / again / good / easy
      //
      // FREE KEYS:
      // - (left)  q w g z x c
      // - (right) p n 8 9 0 , . ; ' [ ]
      "keybinds": {
        // Keybind to toggle between showing the sentence and word on click and hover cards.
        // Equivalent to either clicking on the sentence/word on a click card,
        // or hovering over the word on a hover card.
        "toggle-hybrid-sentence": ["n"],

        // Keybind to toggle between showing the tested word in a raw sentence card.
        // Equivalent to clicking on the "show" button.
        // This is the same as the above because both should never happen at the same time.
        "toggle-highlight-word": ["n"],

        // Keybind to toggle a vocab card's full sentence display (front side).
        // Techinically can be Shift / n as it doesn't interfere with the other two above.
        "toggle-front-full-sentence-display": ["'"],

        "play-sentence-audio": ["p"],

        "play-word-audio": ["w"],

        // Equivalent to toggling the hint show/hide
        "toggle-hint-display": ["."],

        "toggle-secondary-definitions-display": ["8"],

        "toggle-additional-notes-display": ["9"],

        "toggle-extra-definitions-display": ["0"],

        "toggle-extra-info-display": ["["]
      },


      "modules": {

        // Automatic processing to sentences
        "sent-utils": {
          "enabled": true,

          // Removes all line breaks on the regular sentence (if AltDisplay is not filled)
          // TODO mobile true, desktop false
          "remove-line-breaks": false,

          // Removes all line breaks on the AltDisplay sentence
          // TODO mobile true, desktop false
          "remove-line-breaks-on-altdisplay": false,

          // colors the quotes instead of showing a pitch accent indicator
          // if this is enabled
          // TODO mobile true, desktop false
          "pa-indicator-color-quotes": false,

          // automatically colors the quote with the sentence pa indicator color,
          // on PA sentence cards
          "pa-sent-pa-indicator-color-quotes": false,

          // automatically adds quotes to the sentence (if not alt display)
          "auto-quote-sentence": true,

          // automatically adds quotes to the sentence (if alt display)
          "auto-quote-alt-display-sentence": true,

          // the quote pair to automatically add to the sentence
          // NOTE: these are the quotes that are used by default on all sentences even
          // if this module is disabled.
          "auto-quote-open": "「",
          "auto-quote-close": "」",

          // the quote pair to automatically add to the sentence if it's a PA sentence card
          "pa-sent-auto-quote-open": "『",
          "pa-sent-auto-quote-close": "』",

          // quotes to search for on existing sentences,
          // to not double-quote a sentence that already has quotes on it
          "quote-match-strings": [
            ["「", "」"],
            ["『", "』"]
          ]
        },


        // Hover over a kanji in the word reading to see if it has been used
        // in previous cards or not.
        "kanji-hover": {
          "enabled": true,

          // 0: loads every time, slower to reveal the back side of the card
          // 1: loads only upon hover, has a small delay upon first hovering over a word
          "mode": 1,

          // all queries will have the following at the beginning:
          // (-"Key:{{Key}}" Word:*${character}* "card:${cardTypeName}")

          // not new, or new and green
          // not flagged as red and suspended
          "non-new-query": "(-is:new OR (is:new flag:3)) -(is:suspended flag:1)",

          // new
          // not suspended, and neither flagged as red or green
          "new-query": "is:new -(is:suspended (flag:1 OR flag:3))",

          // maximum number of words per category
          "max-non-new-oldest": 2,
          "max-non-new-latest": 2,
          "max-new-latest": 2
        },


        // Automatically selects and displays pitch accent based off of the related fields.
        "auto-pitch-accent": {
          "enabled": true,

          // the reading display to show if nothing is generated by the AJT Pitch Accent plugin
          // (by default, it attempts to find the word within the AJTWordPitch field,
          //  which is usually katakana with long vowel marks.)
          // 0: hiragana
          // 1: katakana
          // 2: katakana with long vowel marks
          "reading-display-mode": 1,

          // whether to search for the ajt word, given the field is filled out
          "search-for-ajt-word": true,

          // Undulation/kifuku (起伏) value, to set the pattern to kifuku
          // (used in the PAOverride field).
          // This sets the downstep be right before the last mora, and colors the word
          // purple if colored-pitch-accent is enabled.
          // Note that these values must be numbers and they CANNOT be strings.
          "kifuku-override": [-1],

          // Whether to color the tested word by pitch accent class or not.
          // Generally: 平板 is blue, 頭高 is red, 中高 is orange and 尾高 is green.
          // The exact colors can be changed in the css.
          // NOTE: There are certain cases where the position cannot be inferred.
          //  See here for more details:
          //  https://aquafina-water-bottle.github.io/jp-mining-note/autopa/#colored-pitch-accent
          "colored-pitch-accent": {
            "enabled": false,

            // Word reading
            "color-reading": true,

            // Tested content (word or sentence).
            // NOTE: this preserves the semantics of whether the sentence
            //     had a highlighted word in the first place. For example,
            //     a sentence card will NOT have the word within the sentence colored,
            //     but a TSC will have the word colored.
            "color-display": true,

            // Pitch accent overline
            "color-overline": true
          }
        },


        // image utilities
        "img-utils": {
          // HIGHLY recommend to be enabled as this doesn't take much javascript
          // and makes things look infinitely better
          "enabled": true,

          // Replaces all images in the glossary (definition) sections
          // with an internal representation similar to how Yomichan displays images:
          // an `[Image]` text where you can see the image upon hover, and with click to zoom.
          "stylize-images-in-glossary": true,

          "nsfw-toggle": {
            // allows the user to mark any card as NSFW, and adds various
            // GUI elements to faciliate just that.
            "enabled": false,

            // what tags can be used to toggle the card between nsfw / not nsfw
            // case sensitive
            "tags": ["NSFW", "nsfw", "-NSFW"],

            // Sets whether nsfw images are blurred by default or not.
            //
            // Available states:
            //  0: all images will not be blurred (even if marked as NSFW)
            //  1: only images marked as NSFW will be blurred by default
            //  2: all images will be blurred regardless of whether it is marked as NSFW or not
            //
            // The first number of the list is the default state. The states cycle from left -> right
            // For example, if the list was [1, 2, 0], it would start at state 1, and clicking on the
            // settings eye will set it to state 2, state 0, state 1, state 2.
            //
            // Note: It is expected that there is at least one state in the list.

            // default for non-mobile devices (usually PC)
            //"toggle-states-pc": [1, 0],
            "toggle-states-pc": [1, 2, 0],

            // default for mobile devices
            "toggle-states-mobile": [1, 2, 0]
          }

        },


        // Opens the specified collapsable field if the card is new.
        "customize-open-fields": {
          "enabled": false,

          "open": [
            // `Primary Definition` only affects cloze-deletion cards, as the primary definition field there is
            // indeed collapsed by default.

            //"Primary Definition",
            //"Secondary Definition",
            //"Additional Notes",
            //"Extra Definitions",
            //"Extra Info"
          ],

          "open-on-new": [
            // `Primary Definition` only affects cloze-deletion cards, as the primary definition field there is
            // indeed collapsed by default.

            //"Primary Definition",
            //"Secondary Definition",
            //"Additional Notes",
            //"Extra Definitions",
            "Extra Info"
          ]
        }
      },


      // Errors that contain the following the following strings will be ignored and not displayed.
      "ignored-errors": [
        // This error is caused by the "Edit Field During Review (Cloze)" add-on.
        // However, this error only appears during the preview and edit cards template windows.
        // This error does not appear to actually affect any of the internal javascript within the card,
        // and is rather caused by the add-on itself.
        // Due to the card's error catcher, this previously-silent error is now caught and shown
        // in the card's error log, despite it not actually affecting anything.
        // Therefore, this error can be safely ignored.
        "ReferenceError: EFDRC is not defined."
      ],

      // Overrides the play keybind button to show the sentence if the
      // card is a hybrid sentence AND the sentence is not currently being shown.
      // Only affects the front side.
      "hybrid-sentence-open-on-play-sentence": true,

      // By default, the indicator for collapsable fields are completely removed.
      // Making this true keeps the indicator, but greys out the text to show that
      // it cannot be opened.
      "greyed-out-collapsable-fields-when-empty": false,

      // Warn if using the `Sentence` field instead of the `SentenceReading` field
      "no-sentence-reading-warn": false,

      // Whether the user can lock the tooltip by clicking on the info-circle or not
      "info-circle-togglable-lock": true,

      // (Developer option) Used to show debug messages when debugging the card.
      // Use the `LOGGER.debug()` (or `logger.debug()`) function in javascript to write debug messages.
      // Set to any number higher than 5 to disable.
      // 0 produces the most debug messages, 5 produces the least debug messages.
      "debug-level": 6
    }

  return my;
}(JPMNOpts || {}));
