# THANK YOU https://github.com/friedrich-de/AnimecardsWebsite
# for putting the site on github so I can easily copy/paste settings

site_name: jp-mining-note
site_description: Documentation for the jp-mining-note project.

repo_url: https://github.com/Aquafina-water-bottle/jp-mining-note
repo_name: jp-mining-note
#edit_uri: edit/master/docs/docs/
edit_uri: edit/dev/docs/docs/
#site_url: https://aquafina-water-bottle.github.io/jp-mining-note/
site_url: https://aquafina-water-bottle.github.io/jp-mining-note-prerelease/

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


  #favicon: assets/smallmarisa.png
  features:
    # single page application
    - navigation.instant

    # table of contents automatically scrolls
    - toc.follow

    # hides the header when you scroll down long enough
    - header.autohide

    - navigation.tabs
    - navigation.sections

    - content.code.annotate

    # copy-to-clipboard buttons for all code blocks
    - content.code.copy

    # view source
    - content.action.view

    # arrows <- and -> in footer
    - navigation.footer

  icon:
    repo: fontawesome/brands/github


plugins:
  - search
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "100%"
      is_video: True
      video_autoplay: False
  - macros
  - git-revision-date-localized:
  - redirects:
      redirect_maps:
        'setupeverythingelse.md': 'setuptextmedia.md'

nav:
  - Home:
    - Home (TODO): index.md
    - Getting Started:
      - Preface: preface.md
      - Alternatives: alternatives.md
  - Setup:
    - "Setup: Installing": setup.md
    - "Setup: Anki": setupanki.md
    - "Setup: Yomichan": setupyomichan.md
    - "Setup: Text & Media": setuptextmedia.md
    - Extra Setup:
      - "Extra: Yomichan": setupextrayomichan.md
      - "Extra: Anki": setupextraanki.md
      - "Extra: Android": setupandroid.md
      - "Extra: iOS": setupios.md
      - "Extra: eReaders": setupereaders.md
      - Transfer Existing Notes: importing.md
    - Updating:
      - Updating: updating.md
      - Setup Changes: setupchanges.md
  - Reference:
    - Quick Start (TODO): quickstart.md
    - Blockquotes (TODO): blockquotes.md
    - Definitions (TODO): definitions.md
    - Sentences (TODO): sentences.md
    - Card Types: cardtypes.md
    - Changing Card Type (TODO): changingcardtype.md
    - More on Card Types (TODO): cardtypes2.md
    - Keybinds: keybinds.md
    - Images: images.md
    - Pitch Accent: autopa.md
    - Kanji Hover (TODO): kanjihover.md
    - Word Indicators (TODO): wordindicators.md
    - Tooltip Results (TODO): tooltipresults.md
    - Info Circle (TODO): infocircle.md
    - Frequencies (TODO): frequencies.md
    - External Links (TODO): externallinks.md
    - Fields (TODO): fields.md
    - Batch Commands (TODO): batch.md
    - Other (TODO): other.md
    - Options:
      - Runtime Options (TODO): runtimeoptions.md
      - Compile-Time Options (TODO): compiletimeoptions.md
      - Yomichan Template Options (TODO): yomichantemplates.md
   #- DEPRECATED:
   #  - User Interface: ui.md
   #  - UI Customization: uicustomization.md
   #  - Field Reference: fieldref.md
  - Dev Docs:
    - Modding Overview: modding.md
    - Building: building.md
    - Custom CSS (TODO): customcss.md
    - Custom HTML (Overrides) (TODO): overrides.md
    - Custom JS (Modules) (TODO): modules.md
    - "Tips & Tricks (TODO)": moddingtips.md
  - "FAQ & Troubleshooting": faq.md
  - JP Resources:
    - JP Resources: jpresources.md
    - JPMN Handlebars Package: jpmnhandlebars.md
    - Anki Scripts (TODO): scripts.md
    - Other: jpresourcesother.md

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - attr_list
  - toc:
      permalink: true
      baselevel: 2
      toc_depth: 3

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys

  - admonition
  - pymdownx.details
  #- pymdownx.superfences

  - md_in_html

  - footnotes

  - pymdownx.tasklist

  # allows strikethrough
  - pymdownx.tilde

  # content tabs (left sidebar)
  #- pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

