# THANK YOU https://github.com/friedrich-de/AnimecardsWebsite
# for putting the site on github so I can easily copy/paste settings

site_name: jp-mining-note
site_description: Documentation for the jp-mining-note project.

repo_url: https://github.com/Aquafina-water-bottle/jp-mining-note
repo_name: jp-mining-note

theme:
  name: material
  custom_dir: docs/overrides

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


  #logo: assets/ideogram-cjk-variant.svg
  #favicon: assets/smallmarisa.png
  features:
    - navigation.instant
    - header.autohide
    - navigation.sections
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github


plugins:
  - search
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "100%"
      is_video: True
      video_autoplay: False
  - macros

nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Card Types: cardtypes.md
  - Transfer Existing Notes: importing.md
  - Updating (TODO): updating.md
  - "Modding & Dev Docs (TODO)": modding.md
  - FAQ (TODO): faq.md
  - Various Resources: jpresources.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - attr_list
  - toc:
      permalink: true
      baselevel: 2
      toc_depth: 3

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition
  - pymdownx.details
  #- pymdownx.superfences

  - md_in_html

  #- pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

