# THANK YOU https://github.com/friedrich-de/AnimecardsWebsite
# for putting the site on github so I can easily copy/paste settings

site_name: jp-mining-note
site_description: Documentation for the jp-mining-note project.

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: black
  #logo: assets/ideogram-cjk-variant.svg
  #favicon: assets/smallmarisa.png
  features:
    - navigation.instant
    - header.autohide
    - navigation.sections
    - content.code.annotate

plugins:
  - search
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "100%"
      is_video: True
      video_autoplay: False
  - macros

nav:
  - Home: index.md
  - Preface: preface.md
  - Setup: setup.md
  - Usage: usage.md
  - Card Types: cardtypes.md
  - Transfer Existing Notes: importing.md
  - Updating the Note (TODO): updating.md
  - "Modding & Dev Docs (TODO)": modding.md
  - FAQ (TODO): faq.md
  - Various Resources: jpresources.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - attr_list
  - toc:
      permalink: true
      baselevel: 2
      toc_depth: 3

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - md_in_html
